pipeline {
    agent {
        node {
            label 'nodejs-agent'
        }
    }

    environment {
        ACC_ID = "12233333334"
        PROJECT = configMap.get("project")
        COMPONENT = configMap.get("component")
    }

    options {
        timeout(time: 10, unit: 'MINUTES') 
        disableConcurrentBuilds()
    }

    stages {

        stage('Read Version') {
            steps {
                script{
                    def packageJSON = readJSON file: 'package.json'
                    appVersion = packageJSON.version
                    echo "app version: ${appVersion}"
                }
            }
        }

        stage('Install Dependencies') {
            steps {
                script{
                    sh "npm install"
                }
            }
        }

        stage('Unit Test') {
            steps {
                script{
                    sh "npm test"
                }
            }
        }

        stage('Sonar Scan'){
            environment {
                scannerHome = tool 'sonar-8.0'
            }
            steps {
                script{
                    withSonarQubeEnv('sonar-server') {
                        sh  "${scannerHome}/bin/sonar-scanner"
                    }
                }
            }
        }

        stage('Quality Gate') {
            steps {
                timeout(time: 1, unit: 'HOURS') {
                    waitForQualityGate abortPipeline: true 
                }
            }
        } 

       stage('Build Image') {
            steps {
               script {
            withCredentials([usernamePassword(
                    credentialsId: 'docker-creds',
                    usernameVariable: 'DOCKER_USER',
                     passwordVariable: 'DOCKER_PASS'
            )]) {
                sh """
                    echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin

                    docker build -t $DOCKER_USER/${PROJECT}-${COMPONENT}:${appVersion} .

                    docker push $DOCKER_USER/${PROJECT}-${COMPONENT}:${appVersion}
                """
            }
        }
    }
}

        stage('Deploy to EKS') {
            steps {
                script {
                    withAWS(region: 'us-east-1', credentials: 'aws-creds') {
                        sh """
                            # Connect to EKS cluster
                            aws eks update-kubeconfig --region us-east-1 --name ${PROJECT}-dev

                            # Verify cluster
                            kubectl get nodes

                            # Apply Kubernetes manifests
                            kubectl apply -f k8s/manifest.yaml

                            # Wait for rollout
                            kubectl rollout status deployment/${COMPONENT} -n ${PROJECT}
                        """
                    }
                }
            }
        }


    }

    post{
        always{
            echo 'I will always say Hello again!'
            cleanWs()
        }
        success {
            echo 'I will run if success'
        }
        failure {
            echo 'I will run if failure'
        }
        aborted {
            echo 'pipeline is aborted'
        }
    }
}